var DRIVE_VENDOR_TYPE_VHP = 1;
var DRIVE_VENDOR_TYPE_VIBM = 2;
var DRIVE_VENDOR_TYPE_VQUANTUM = 3;
var DRIVE_VENDOR_TYPE_VSTK = 4;

var LIBRARY_VENDOR_TYPE_VADIC = 1;
var LIBRARY_VENDOR_TYPE_VHP = 2;
var LIBRARY_VENDOR_TYPE_VIBM = 3;
var LIBRARY_VENDOR_TYPE_VOVL = 4;
var LIBRARY_VENDOR_TYPE_VSTK = 5;
var LIBRARY_VENDOR_TYPE_VSPECTRA = 6;
var LIBRARY_VENDOR_TYPE_VQUANTUM = 7;

var DRIVE_TYPE_VHP_DLTVS80 = 1;
var DRIVE_TYPE_VHP_DLTVS160 = 2;
var DRIVE_TYPE_VHP_SDLT220 = 3;
var DRIVE_TYPE_VHP_SDLT320 = 4;
var DRIVE_TYPE_VHP_SDLT600 = 5;
var DRIVE_TYPE_VQUANTUM_SDLT220 = 6;
var DRIVE_TYPE_VQUANTUM_SDLT320 = 7;
var DRIVE_TYPE_VQUANTUM_SDLT600 = 8;
var DRIVE_TYPE_VHP_ULT232 = 9;
var DRIVE_TYPE_VHP_ULT448 = 10;
var DRIVE_TYPE_VHP_ULT460 = 11;
var DRIVE_TYPE_VHP_ULT960 = 12;
var DRIVE_TYPE_VHP_ULT1840 = 13;
var DRIVE_TYPE_VHP_ULT3280 = 14;
var DRIVE_TYPE_VHP_ULT6250 = 15;
var DRIVE_TYPE_VIBM_3580ULT1 = 16;
var DRIVE_TYPE_VIBM_3580ULT2 = 17;
var DRIVE_TYPE_VIBM_3580ULT3 = 18;
var DRIVE_TYPE_VIBM_3580ULT4 = 19;
var DRIVE_TYPE_VIBM_3580ULT5 = 20;
var DRIVE_TYPE_VIBM_3580ULT6 = 21;
var DRIVE_TYPE_VSTK_T9840A = 22;
var DRIVE_TYPE_VSTK_T9840B = 23;
var DRIVE_TYPE_VSTK_T9840C = 24;
var DRIVE_TYPE_VSTK_T9840D = 25;
var DRIVE_TYPE_VSTK_T9940A = 26;
var DRIVE_TYPE_VSTK_T9940B = 27;
var DRIVE_TYPE_VSTK_T10000A = 28;
var DRIVE_TYPE_VSTK_T10000B = 29;
var DRIVE_TYPE_VSTK_T10000C = 30;
var DRIVE_TYPE_VQUANTUM_DLTVS80 = 31;
var DRIVE_TYPE_VQUANTUM_DLTVS160 = 32;

var LIBRARY_TYPE_VADIC_SCALAR24 = 1;
var LIBRARY_TYPE_VADIC_SCALAR100 = 2;
var LIBRARY_TYPE_VADIC_SCALARi2000 = 3;
var LIBRARY_TYPE_VHP_ESL9000 = 4;
var LIBRARY_TYPE_VHP_ESLSERIES = 5;
var LIBRARY_TYPE_VHP_EMLSERIES = 6;
var LIBRARY_TYPE_VIBM_3583 = 7;
var LIBRARY_TYPE_VIBM_3584 = 8;
var LIBRARY_TYPE_VIBM_TS3100 = 9;
var LIBRARY_TYPE_VHP_MSLSERIES = 10;
var LIBRARY_TYPE_VHP_MSL6000 = 11;
var LIBRARY_TYPE_VOVL_NEOSERIES = 12;
var LIBRARY_TYPE_VSTK_L20 = 13;
var LIBRARY_TYPE_VSTK_L40 = 14;
var LIBRARY_TYPE_VSTK_L80 = 15;
var LIBRARY_TYPE_VSTK_L120 = 16;
var LIBRARY_TYPE_VSTK_L180 = 17;
var LIBRARY_TYPE_VSTK_L700 = 18;
var LIBRARY_TYPE_VSTK_L1400 = 19;
var LIBRARY_TYPE_VSTK_SL150 = 20;
var LIBRARY_TYPE_VSTK_SL500 = 21;
var LIBRARY_TYPE_VSTK_SL3000 = 22;
var LIBRARY_TYPE_VSTK_SL8500 = 23;
var LIBRARY_TYPE_VSPECTRA_2K = 24;
var LIBRARY_TYPE_VSPECTRA_20K = 25;
var LIBRARY_TYPE_VSPECTRA_T24 = 26;
var LIBRARY_TYPE_VSPECTRA_TSERIES = 27;
var LIBRARY_TYPE_VADIC_SCALAR50 = 28;
var LIBRARY_TYPE_VADIC_SCALARi4080 = 29;
var LIBRARY_TYPE_VADIC_SCALARi500 = 30;
var LIBRARY_TYPE_VADIC_SCALARi6000 = 31;
var LIBRARY_TYPE_VQUANTUM_M1500 = 32;
var LIBRARY_TYPE_VQUANTUM_M2500 = 33;
var LIBRARY_TYPE_VQUANTUM_P1000 = 34;
var LIBRARY_TYPE_VQUANTUM_P2000 = 35;
var LIBRARY_TYPE_VQUANTUM_P3000 = 36;
var LIBRARY_TYPE_VQUANTUM_P4000 = 37;
var LIBRARY_TYPE_VQUANTUM_P7000 = 38;
var LIBRARY_TYPE_VQUANTUM_PX500 = 39;
var LIBRARY_TYPE_VQUANTUM_PX720 = 40;

var drivevendors = new Array(
	new Array("HP", DRIVE_VENDOR_TYPE_VHP),
	new Array("IBM", DRIVE_VENDOR_TYPE_VIBM),
	new Array("Quantum", DRIVE_VENDOR_TYPE_VQUANTUM),
	new Array("StorageTek", DRIVE_VENDOR_TYPE_VSTK)
);

var libraryvendors = new Array(
	new Array("ADIC", LIBRARY_VENDOR_TYPE_VADIC),
	new Array("HP", LIBRARY_VENDOR_TYPE_VHP),
	new Array("IBM", LIBRARY_VENDOR_TYPE_VIBM),
	new Array("Overland", LIBRARY_VENDOR_TYPE_VOVL),
	new Array("StorageTek", LIBRARY_VENDOR_TYPE_VSTK),
	new Array("SpectraLogic", LIBRARY_VENDOR_TYPE_VSPECTRA),
	new Array("QUANTUM", LIBRARY_VENDOR_TYPE_VQUANTUM)
);

var drivetypes = new Array(
	new Array("HP StorageWorks DLT VS80", DRIVE_TYPE_VHP_DLTVS80),
	new Array("HP StorageWorks DLT VS160", DRIVE_TYPE_VHP_DLTVS160),
	new Array("HP StorageWorks SDLT 220", DRIVE_TYPE_VHP_SDLT220),
	new Array("HP StorageWorks SDLT 320", DRIVE_TYPE_VHP_SDLT320),
	new Array("HP StorageWorks SDLT 600", DRIVE_TYPE_VHP_SDLT600),
	new Array("Quantum SDLT 220", DRIVE_TYPE_VQUANTUM_SDLT220),
	new Array("Quantum SDLT 320", DRIVE_TYPE_VQUANTUM_SDLT320),
	new Array("Quantum SDLT 600", DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array("HP StorageWorks Ultrium 232", DRIVE_TYPE_VHP_ULT232),
	new Array("HP StorageWorks Ultrium 448", DRIVE_TYPE_VHP_ULT448),
	new Array("HP StorageWorks Ultrium 460", DRIVE_TYPE_VHP_ULT460),
	new Array("HP StorageWorks Ultrium 960", DRIVE_TYPE_VHP_ULT960),
	new Array("HP StorageWorks Ultrium 1840", DRIVE_TYPE_VHP_ULT1840),
	new Array("HP StoreEver Ultrium 3280", DRIVE_TYPE_VHP_ULT3280),
	new Array("HP StoreEver Ultrium 6250", DRIVE_TYPE_VHP_ULT6250),
	new Array("IBM 3580 Ultrium1", DRIVE_TYPE_VIBM_3580ULT1),
	new Array("IBM 3580 Ultrium2", DRIVE_TYPE_VIBM_3580ULT2),
	new Array("IBM 3580 Ultrium3", DRIVE_TYPE_VIBM_3580ULT3),
	new Array("IBM 3580 Ultrium4", DRIVE_TYPE_VIBM_3580ULT4),
	new Array("IBM 3580 Ultrium5", DRIVE_TYPE_VIBM_3580ULT5),
	new Array("IBM 3580 Ultrium6", DRIVE_TYPE_VIBM_3580ULT6),
	new Array( "StorageTek T9840A", DRIVE_TYPE_VSTK_T9840A),
	new Array( "StorageTek T9840B", DRIVE_TYPE_VSTK_T9840B),
	new Array( "StorageTek T9840C", DRIVE_TYPE_VSTK_T9840C),
	new Array( "StorageTek T9840D", DRIVE_TYPE_VSTK_T9840D),
	new Array( "StorageTek T9940A", DRIVE_TYPE_VSTK_T9940A),
	new Array( "StorageTek T9940B", DRIVE_TYPE_VSTK_T9940B),
	new Array( "StorageTek T10000A", DRIVE_TYPE_VSTK_T10000A),
	new Array( "StorageTek T10000B", DRIVE_TYPE_VSTK_T10000B),
	new Array( "StorageTek T10000C", DRIVE_TYPE_VSTK_T10000C),
	new Array("Quantum DLT VS80", DRIVE_TYPE_VQUANTUM_DLTVS80),
	new Array("Quantum DLT VS160", DRIVE_TYPE_VQUANTUM_DLTVS160)
);

var librarytypes = new Array(
	new Array("ADIC Scalar 24", LIBRARY_TYPE_VADIC_SCALAR24),
	new Array("ADIC Scalar 100", LIBRARY_TYPE_VADIC_SCALAR100),
	new Array("ADIC Scalar i2000", LIBRARY_TYPE_VADIC_SCALARi2000),
	new Array("HP StorageWorks ESL9000", LIBRARY_TYPE_VHP_ESL9000),
	new Array("HP StorageWorks ESL E-Series", LIBRARY_TYPE_VHP_ESLSERIES),
	new Array("HP StorageWorks EML E-Series", LIBRARY_TYPE_VHP_EMLSERIES),
	new Array("IBM 3583 Ultrium Scalable Library", LIBRARY_TYPE_VIBM_3583),
	new Array("IBM 3584 Ultra Scalable Library", LIBRARY_TYPE_VIBM_3584),
	new Array("IBM IBM System Storage TS3100", LIBRARY_TYPE_VIBM_TS3100),
	new Array("HP StorageWorks MSL 2024/4048/8096", LIBRARY_TYPE_VHP_MSLSERIES),
	new Array("HP StorageWorks MSL 6000", LIBRARY_TYPE_VHP_MSL6000),
	new Array("Overland NEO 2000/4000/8000 Series", LIBRARY_TYPE_VOVL_NEOSERIES),
	new Array("StorageTek L20 Library", LIBRARY_TYPE_VSTK_L20),
	new Array("StorageTek L40 Library", LIBRARY_TYPE_VSTK_L40),
	new Array("StorageTek L80 Library", LIBRARY_TYPE_VSTK_L80),
	new Array("StorageTek L120 Library", LIBRARY_TYPE_VSTK_L120),
	new Array("StorageTek L180 Library", LIBRARY_TYPE_VSTK_L180),
	new Array("StorageTek L700 Library", LIBRARY_TYPE_VSTK_L700),
	new Array("StorageTek L1400/700e Library", LIBRARY_TYPE_VSTK_L1400),
	new Array("StorageTek SL150 Modular Library", LIBRARY_TYPE_VSTK_SL150),
	new Array("StorageTek SL500 Modular Library", LIBRARY_TYPE_VSTK_SL500),
	new Array("StorageTek SL3000 Modular Library", LIBRARY_TYPE_VSTK_SL3000),
	new Array("StorageTek SL8500 Modular Library", LIBRARY_TYPE_VSTK_SL8500),
	new Array("SpectraLogic 2K/TreeFrog Library", LIBRARY_TYPE_VSPECTRA_2K),
	new Array("SpectraLogic 12/20/64K Library", LIBRARY_TYPE_VSPECTRA_20K),
	new Array("SpectraLogic T24 Library", LIBRARY_TYPE_VSPECTRA_T24),
	new Array("SpectraLogic T-Series Library", LIBRARY_TYPE_VSPECTRA_TSERIES),
	new Array("Quantum/ADIC Scalar 50", LIBRARY_TYPE_VADIC_SCALAR50),
	new Array("Quantum/ADIC Scalar i40/80 Series", LIBRARY_TYPE_VADIC_SCALARi4080),
	new Array("Quantum/ADIC Scalar i500", LIBRARY_TYPE_VADIC_SCALARi500),
	new Array("Quantum/ADIC Scalar i6000", LIBRARY_TYPE_VADIC_SCALARi6000),
	new Array("ATL M1500", LIBRARY_TYPE_VQUANTUM_M1500),
	new Array("ATL M2500", LIBRARY_TYPE_VQUANTUM_M2500),
	new Array("ATL P1000", LIBRARY_TYPE_VQUANTUM_P1000),
	new Array("ATL P2000", LIBRARY_TYPE_VQUANTUM_P2000),
	new Array("ATL P3000", LIBRARY_TYPE_VQUANTUM_P3000),
	new Array("ATL P4000", LIBRARY_TYPE_VQUANTUM_P4000),
	new Array("ATL P7000", LIBRARY_TYPE_VQUANTUM_P7000),
	new Array("Quantum PX500 Series", LIBRARY_TYPE_VQUANTUM_PX500),
	new Array("Quantum PX720", LIBRARY_TYPE_VQUANTUM_PX720)
);

var vendordrivetypes = new Array(
	new Array(DRIVE_VENDOR_TYPE_VHP, DRIVE_TYPE_VHP_DLTVS80, DRIVE_TYPE_VHP_DLTVS160, DRIVE_TYPE_VHP_SDLT220, DRIVE_TYPE_VHP_SDLT320, DRIVE_TYPE_VHP_SDLT600, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT448, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(DRIVE_VENDOR_TYPE_VIBM, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(DRIVE_VENDOR_TYPE_VSTK, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9840D, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C),
	new Array(DRIVE_VENDOR_TYPE_VQUANTUM, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600)
);

var vendorlibrarytypes = new Array(
	new Array(LIBRARY_VENDOR_TYPE_VADIC, LIBRARY_TYPE_VADIC_SCALAR24, LIBRARY_TYPE_VADIC_SCALAR100, LIBRARY_TYPE_VADIC_SCALARi2000, LIBRARY_TYPE_VADIC_SCALAR50, LIBRARY_TYPE_VADIC_SCALARi4080, LIBRARY_TYPE_VADIC_SCALARi500, LIBRARY_TYPE_VADIC_SCALARi6000),
	new Array(LIBRARY_VENDOR_TYPE_VHP, LIBRARY_TYPE_VHP_ESL9000, LIBRARY_TYPE_VHP_ESLSERIES, LIBRARY_TYPE_VHP_EMLSERIES, LIBRARY_TYPE_VHP_MSLSERIES, LIBRARY_TYPE_VHP_MSL6000),
	new Array(LIBRARY_VENDOR_TYPE_VIBM, LIBRARY_TYPE_VIBM_3583, LIBRARY_TYPE_VIBM_3584, LIBRARY_TYPE_VIBM_TS3100),
	new Array(LIBRARY_VENDOR_TYPE_VOVL, LIBRARY_TYPE_VOVL_NEOSERIES),
	new Array(LIBRARY_VENDOR_TYPE_VSTK, LIBRARY_TYPE_VSTK_L20, LIBRARY_TYPE_VSTK_L40, LIBRARY_TYPE_VSTK_L80, LIBRARY_TYPE_VSTK_L120, LIBRARY_TYPE_VSTK_L180, LIBRARY_TYPE_VSTK_L700, LIBRARY_TYPE_VSTK_L1400, LIBRARY_TYPE_VSTK_SL150, LIBRARY_TYPE_VSTK_SL500, LIBRARY_TYPE_VSTK_SL3000, LIBRARY_TYPE_VSTK_SL8500),
	new Array(LIBRARY_VENDOR_TYPE_VSPECTRA, LIBRARY_TYPE_VSPECTRA_2K, LIBRARY_TYPE_VSPECTRA_20K, LIBRARY_TYPE_VSPECTRA_T24, LIBRARY_TYPE_VSPECTRA_TSERIES),
	new Array(LIBRARY_VENDOR_TYPE_VQUANTUM, LIBRARY_TYPE_VQUANTUM_M1500, LIBRARY_TYPE_VQUANTUM_M2500, LIBRARY_TYPE_VQUANTUM_P1000, LIBRARY_TYPE_VQUANTUM_P2000, LIBRARY_TYPE_VQUANTUM_P3000, LIBRARY_TYPE_VQUANTUM_P4000, LIBRARY_TYPE_VQUANTUM_P7000, LIBRARY_TYPE_VQUANTUM_PX500, LIBRARY_TYPE_VQUANTUM_PX720)
);

var librarydrivetypes = new Array(
	new Array(LIBRARY_TYPE_VADIC_SCALAR24, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4),
	new Array(LIBRARY_TYPE_VADIC_SCALAR100, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4),
	new Array(LIBRARY_TYPE_VADIC_SCALARi2000, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VHP_ESL9000, DRIVE_TYPE_VHP_SDLT220, DRIVE_TYPE_VHP_SDLT320, DRIVE_TYPE_VHP_SDLT600, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960),
	new Array(LIBRARY_TYPE_VHP_ESLSERIES, DRIVE_TYPE_VHP_SDLT220, DRIVE_TYPE_VHP_SDLT320, DRIVE_TYPE_VHP_SDLT600, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840),
	new Array(LIBRARY_TYPE_VHP_EMLSERIES, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VIBM_3583, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3),
	new Array(LIBRARY_TYPE_VIBM_3584, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VIBM_TS3100, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VHP_MSLSERIES, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VHP_MSL6000, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VOVL_NEOSERIES, DRIVE_TYPE_VHP_ULT232, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_L20, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VSTK_L40, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VSTK_L80, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VSTK_L120, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VSTK_L180, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_L700, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_L1400, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_SL150, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VSTK_SL500, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_SL3000, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSTK_SL8500, DRIVE_TYPE_VSTK_T9840A, DRIVE_TYPE_VSTK_T9840B, DRIVE_TYPE_VSTK_T9840C, DRIVE_TYPE_VSTK_T9940A, DRIVE_TYPE_VSTK_T9940B, DRIVE_TYPE_VSTK_T10000A, DRIVE_TYPE_VSTK_T10000B, DRIVE_TYPE_VSTK_T10000C, DRIVE_TYPE_VHP_ULT460, DRIVE_TYPE_VHP_ULT960, DRIVE_TYPE_VHP_ULT1840, DRIVE_TYPE_VHP_ULT3280, DRIVE_TYPE_VHP_ULT6250),
	new Array(LIBRARY_TYPE_VSPECTRA_2K, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VSPECTRA_20K, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VSPECTRA_T24, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VSPECTRA_TSERIES, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VADIC_SCALAR50, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VADIC_SCALARi4080, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VADIC_SCALARi500, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VADIC_SCALARi6000, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VQUANTUM_M1500, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3),
	new Array(LIBRARY_TYPE_VQUANTUM_M2500, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3),
	new Array(LIBRARY_TYPE_VQUANTUM_P1000, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VQUANTUM_P2000, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600),
	new Array(LIBRARY_TYPE_VQUANTUM_P3000, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3),
	new Array(LIBRARY_TYPE_VQUANTUM_P4000, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VQUANTUM_P7000, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VQUANTUM_PX500, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6),
	new Array(LIBRARY_TYPE_VQUANTUM_PX720, DRIVE_TYPE_VQUANTUM_SDLT220, DRIVE_TYPE_VQUANTUM_SDLT320, DRIVE_TYPE_VQUANTUM_SDLT600, DRIVE_TYPE_VIBM_3580ULT1, DRIVE_TYPE_VIBM_3580ULT2, DRIVE_TYPE_VIBM_3580ULT3, DRIVE_TYPE_VIBM_3580ULT4, DRIVE_TYPE_VIBM_3580ULT5, DRIVE_TYPE_VIBM_3580ULT6)
);

function getdrivetype(dtype)
{
	for (var i = 0; i < drivetypes.length; i++) {
		drivetypearr = drivetypes[i];
		if (drivetypearr[1] == dtype)
			return drivetypearr;
	}
	return null;
}

function getlibrarytype(ltype)
{
	for (var i = 0; i < librarytypes.length; i++) {
		librarytypearr = librarytypes[i];
		if (librarytypearr[1] == ltype)
			return librarytypearr;
	}
	return null;
}

function filldriveforlibrary()
{
	var frm = document.getElementById('J_ajaxForm');
	var dindex = frm.librarytype.value;
	var drivearr;

	while (frm.drivetype0.length > 0)
		frm.drivetype0.remove(0);

	for (var i = 0; i < librarydrivetypes.length; i++) {
		drivearr = librarydrivetypes[i];
		if (drivearr[0] == dindex) {
			break;
		}
	}

	for (var i = 1; i < drivearr.length; i++) {
		var dtype = drivearr[i];
		var vtlval = getdrivetype(dtype);
		var isselected;

		isselected = i == 1 ? true : false ;
		frm.drivetype0.options[i - 1] = new Option(vtlval[0], vtlval[1], isselected, false);
	}
}

function fillvtldrivetypes()
{
	var frm = document.getElementById('J_ajaxForm');
	var dindex = frm.librarytype.value;
	var drivearr;

	while (frm.driveselect.length > 0)
		frm.driveselect.remove(0);

	for (var i = 0; i < librarydrivetypes.length; i++) {
		drivearr = librarydrivetypes[i];
		if (drivearr[0] == dindex) {
			break;
		}
	}

	for (var i = 1; i < drivearr.length; i++) {
		var dtype = drivearr[i];
		var vtlval = getdrivetype(dtype);
		var isselected;

		isselected = i == 1 ? true : false ;
		frm.driveselect.options[i - 1] = new Option(vtlval[0], vtlval[1], isselected, false);
	}
}

function filldriveforvendor()
{
	var frm = document.getElementById('J_ajaxForm');
	var dindex = frm.drivevendor.value;
	var drivearr;

	while (frm.drivetype0.length > 0)
		frm.drivetype0.remove(0);

	for (var i = 0; i < vendordrivetypes.length; i++) {
		drivearr = vendordrivetypes[i];
		if (drivearr[0] == dindex)
			break;
	}

	for (var i = 1; i < drivearr.length; i++) {
		var dtype = drivearr[i];
		var vtlval = getdrivetype(dtype);
		var isselected;

		isselected = i == 1 ? true : false ;
		frm.drivetype0.options[i - 1] = new Option(vtlval[0], vtlval[1], isselected, false);
	}
}

function filllibraryforvendor()
{
	var frm = document.getElementById('J_ajaxForm');
	var lindex = frm.libraryvendor.value;
	var libraryarr;

	while (frm.librarytype.length > 0)
		frm.librarytype.remove(0);

	for (var i = 0; i < vendorlibrarytypes.length; i++) {
		libraryarr = vendorlibrarytypes[i];
		if (libraryarr[0] == lindex)
			break;
	}

	for (var i = 1; i < libraryarr.length; i++) {
		var ltype = libraryarr[i];
		var vtlval = getlibrarytype(ltype);
		var isselected;

		isselected = i == 1 ? true : false ;
		frm.librarytype.options[i - 1] = new Option(vtlval[0], vtlval[1], isselected, false);
	}
	filldriveforlibrary();
}

function filldrive()
{
	var frm = document.getElementById('J_ajaxForm');

	for (var i = 0; i < drivevendors.length; i++) {
		var vtlval = drivevendors[i];
		if (i == 0)
			frm.drivevendor.options[i] = new Option(vtlval[0], vtlval[1], true, false);
		else
			frm.drivevendor.options[i] = new Option(vtlval[0], vtlval[1], false, false);
	}
	filldriveforvendor();
}

function filllibrary()
{
	var frm = document.getElementById('J_ajaxForm');

	for (var i = 0; i < libraryvendors.length; i++) {
		var vtlval = libraryvendors[i];
		if (i == 0)
			frm.libraryvendor.options[i] = new Option(vtlval[0], vtlval[1], true, false);
		else
			frm.libraryvendor.options[i] = new Option(vtlval[0], vtlval[1], false, false);
	}
	filllibraryforvendor();
}

function ValidString(str){
	var re = /[^a-zA-Z0-9]/

	if (re.test(str))
	{
		return false;
	}
	return true;
}

function isNumeric(str){
	var re = /[\D]/
	if (re.test(str))
	{
		return false;
	}
	return true;
}

function checkform()
{
	var frm = document.getElementById('J_ajaxForm');

	if (frm.slots) {
		slots = parseInt(frm.slots.value, 10);
		if (slots == NaN || !slots || slots > 60000) {
			alert("Number of slots is invalid")
			return false;
		}

		ieports = parseInt(frm.ieports.value, 10);
		if (ieports == NaN || ieports > 250) {
			alert("Number of ieports is invalid")
			return false;
		}

		dtstart = parseInt(frm.dtstart.value, 10);
		if (dtstart == NaN || !dtstart || dtstart >= 65536) {
			alert("Drive start address is invalid")
			return false;
		}

		ststart = parseInt(frm.ststart.value, 10);
		if (ststart == NaN || !ststart || ststart >= 65536) {
			alert("Slot start address is invalid")
			return false;
		}

		iestart = parseInt(frm.iestart.value, 10);
		if (iestart == NaN || !iestart || iestart >= 65536) {
			alert("IE start address is invalid")
			return false;
		}

	}

	if (!frm.name.value) {
		alert("VDrive Name cannot be empty");
		return false;
	}

	if (!ValidString(frm.name.value)) {
		alert("VDrive Name can only contain alphabets or numbers");
		return false;
	}

	frm.ndrivetype0.value = frm.ndrives.value;
	return true;
}

function checkformadddrive()
{
	var frm = document.getElementById('J_ajaxForm');
	var foundtype;

	ndrives = parseInt(frm.ndrives.value);
	drivetype = frm.driveselect.value;
	drivetype = parseInt(drivetype);

	prevndrivetypes = parseInt(frm.ndrivetypes.value);
	var count = 0;
	for (i = 0; i < prevndrivetypes; i++)
	{
		ndtypesstr = "ndrivetype"+i;
		prevval = frm.elements[ndtypesstr].value;
		count += parseInt(prevval);
	}

	foundtype = 0;
	for (i = 0; i < prevndrivetypes; i++)
	{
		dtypestr = "drivetype"+i;

		dtypeval = frm.elements[dtypestr].value;
		if (parseInt(dtypeval) == drivetype)
		{
			foundtype = 1;
			ndtypesstr = "ndrivetype"+i;
			prevval = frm.elements[ndtypesstr].value;

			prevval = parseInt(prevval)+ndrives+'';
			frm.elements[ndtypesstr].value = prevval;
			break;
		}

	}

	if (!foundtype)
	{
		var newstr = "drivetype"+prevndrivetypes;
		elem = frm.elements[newstr];

		elem.value = frm.driveselect.value; 
		newstr = "ndrivetype"+prevndrivetypes;
		elem = frm.elements[newstr];
		elem.value = frm.ndrives.value; 

		frm.ndrivetypes.value = prevndrivetypes+1+'';
	}

	return true;
}